ekf_simple_node:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: map     # Truco: Al poner map aquí, el EKF publica la TF directa map -> base_link
    base_link_frame: base_link
    world_frame: map

    # 1. Odometría de ruedas (Apagada al 100%)
    odom0: odom
    odom0_config: [false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    
    # 2. Detección ArUco (absoluta, discreta)
    pose0: aruco_pose
    pose0_config: [true,  true,  false,
                   false, false, true,  # ¡Ahora el EKF absorbe el Yaw de los ArUcos!
                   false, false, false,
                   false, false, false,
                   false, false, false]
